---
title: 'Coursera EDA Quiz #1'
author: "MCCurcio"
date: "12/25/2020"
output: html_document
---

Q1
Which of the following is a principle of analytic graphics?

- Show box plots (univariate summaries)
- Don't plot more than two variables at at time
X Show multivariate data
- Make judicious use of color in your scatterplots
- Only do what your tools allow you to do.


Q2

What is the role of exploratory graphs in data analysis?

- They are made for formal presentations.
X They are typically made very quickly.
- Axes, legends, and other details are clean and exactly detailed.
- Only a few are constructed


Q3

Which of the following is true about the base plotting system?

- Margins and spacings are adjusted automatically depending on the type of plot and the data
X Plots are created and annotated with separate functions
- Plots are typically created with a single function call
- The system is most useful for conditioning plots


Q4

Which of the following is an example of a valid graphics device in R?

X The computer screen
- A socket connection
- The keyboard
- A file folder
- A Microsoft Word document

Q5

Which of the following is an example of a vector graphics device in R?

- TIFF
X Postscript
- PNG
- GIF
- JPEG


Q6

Bitmapped file formats can be most useful for 

- Plots that require animation or interactivity
- Plots that may need to be resized
- Plots that are not scaled to a specific resolution
X Scatterplots with many many points


Q7

Which of the following functions is typically used to add elements to a plot in the base graphics system?

- hist()
X points()
- boxplot()
- plot()


Q8

Which function opens the screen graphics device on Windows?

X windows()
- jpeg()
- xfig()
- postscript()


Q9

What does the 'pch' option to par() control?

- the orientation of the axis labels on the plot
- the line width in the base graphics system
- the size of the plotting symbol in a scatterplot
X the plotting symbol/character in the base graphics system


Q10

If I want to save a plot to a PDF file, which of the following is a correct way of doing that?

- Open the screen device with quartz(), construct the plot, and then close the device with dev.off().
NO Open the PostScript device with postscript(), construct the plot, then close the device with dev.off().
- Construct the plot on the PNG device with png(), then copy it to a PDF with dev.copy2pdf().
YES? Construct the plot on the screen device and then copy it to a PDF file with dev.copy2pdf()




