---
title: Coursera-R programming-Assignment-3
owner: MCurcio
data: 12/9/2020
---



```{r}
best <- function(state = "MA", outcome = "heart attack") {
      # Read .csv
      df = read.csv("outcome-of-care-measures.csv",
                    na.strings = "Not Available",
                    skip = 1,
                    header = FALSE,
                    stringsAsFactors = FALSE)
      
      # Retain only hospital, state, ha, hf, p
      df <- df[,c(2,7,11,17,25)]
      
      all_states <- unique(df[, 2])
      
      # Check for invalid state & outcome
      if (!(outcome %in% c("heart attack", "heart failure", "pneumonia"))) { 
            stop("invalid outcome") 
      } else { 
          #print("outcome OK") 
          switch(outcome,
                 "heart attack"  = (df <- df[, c(1, 2, 3)]),
                 "heart failure" = (df <- df[, c(1, 2, 4)]),
                 "pneumonia"     = (df <- df[, c(1, 2, 5)]))
      }
      if (!(state %in% all_states)) { 
            stop("invalid state") 
      } else { 
            #print("state OK") 
            subset_df  <-  df[df[,2] == state,]
      }
      library(tidyverse)
      subset_df %>% arrange(subset_df[,3], subset_df[,1])
      print(subset_df[1,1])
}
```



```{r}
df <- best()

```


```{r}
df <- best(state = "RI", 
           outcome = "heart attack")

head(df)
```


```{r}
df <- best(state = "Rj", 
           outcome = "heart attack")

head(df)
```

```{r}
df <- best(state = "RI", 
           outcome = "heart battack")

head(df)
```















