title: Coursera-R programming-Assignment-3
owner: MCurcio
data: 12/9/2020

##################################################################
Function: Read ONLY 5 Columns to save memory and speed up program.

```{r}
read_5_columns <- function(file_name = "outcome-of-care-measures.csv") {
      #library("readr")
      df2 = read.table("outcome-of-care-measures.csv", # Read only first of .csv
                      nrows = 1, 
                      header = TRUE,
                      sep = ",",
                      stringsAsFactors = FALSE)
      
      colClasses = as.list(apply(df, 2, class)) # place column names into colClasses list.
      
      # Use ONLY these column names.
      needCols = c("State",
                   "Hospital.Name", 
                   "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack",
                   "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure", 
                   "Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia")
      
      # Null out columns that are not needed.
      colClasses[!names(colClasses) %in% needCols] = list(NULL)
      
      # Read ONLY the columns in `needCols`
      df2 = read.table("outcome-of-care-measures.csv",
                       header = TRUE,
                       sep = ",",
                       na.strings = "NA",
                       stringsAsFactors = FALSE)
      
      # change column names for convenience
      #colnames(df)<-c("Hospital Name","State","Heart Attack","Heart Failure","Pneumonia")
}
```

```{r}
df <- read_5_columns(file_name = "outcome-of-care-measures.csv")

```



```{r}
best <- function(state = "AK", outcome = "pneumonia", ...){
        
      df <- read_5_columns(file_name = "outcome-of-care-measures.csv")
      all_states <- unique(df[, 2])
      outcomes = c("heart attack", "heart failure", "pneumonia")
        
      if (!(outcome %in% outcomes)) { 
            stop("invalid outcome") }
      else { print("outcome OK") }
        
      if (!(state %in% all_states)) { 
            stop("invalid state") }
      else { print("state OK") }
      
      # Alphabetize Hospitals and rank.
}
```


```{r}
best()
```


```{r}
best(state="AL", outcome = "pneumonia")
```

```{r}
best(state="zx", outcome = "pneumonia")
```
```{r}
best(state="AL", outcome = "Neumonia")
```


```{r}
best(state="Ax", outcome = "Neumonia")
```



