---
title: "Quiz week 2"
author: "MCCurcio"
date: "12/27/2020"
output: html_document
---

Coursera Data Cleaning Quiz 2 - Info on JL

```{r}
setwd("~/Dropbox/R_exercises/Coursera/Data_cleaning/week2")
```

```{r}
library(httr)
library(httpuv)
```


```{r}
# 1. Find OAuth settings for github:
#    http://developer.github.com/v3/oauth/
oauth_endpoints("github")
```

```{r}
# 2. To make your own application, register at
#    https://github.com/settings/developers. Use any URL for the homepage URL
#    (http://github.com is fine) and  http://localhost:1410 as the callback url


# Client ID: 00a170d146d53ecb0f1d
# secret = 549af28d71912b6cb5e8d74bf0fce70a055cff23

#    Replace your key and secret below.
myapp <- oauth_app("github",
  key = "00a170d146d53ecb0f1d",
  secret = "549af28d71912b6cb5e8d74bf0fce70a055cff23"
)
print("OK")
```


```{r}
# 3. Get OAuth credentials
github_token <- oauth2.0_token(oauth_endpoints("github"), myapp)
```


```{r}
# 4. Use API
gtoken <- config(token = github_token)
req <- GET("https://api.github.com/rate_limit", gtoken)
stop_for_status(req)
content(req)
```


```{r}
# OR:
req <- with_config(gtoken, GET("https://api.github.com/rate_limit"))
stop_for_status(req)
content(req)
```

