## Exercise 2.2 

- Write a program that uses input to prompt a user for their name and then welcomes them. 
- Note that input will pop up a dialog box. 
- Enter Sarah in the pop-up box when you are prompted so your output will match the desired output.

In [3]:
# The code below almost works

name = input("Enter your name")
print('Hello', name)

Enter your nameSarah
Hello Sarah


## Exercise 2.3 

- Write a program to prompt the user for hours and rate per hour using input to compute gross pay. 
- Use 35 hours and a rate of 2.75 per hour to test the program (the pay should be 96.25). 
- You should use input to read a string and float() to convert the string to a number. 
- Do not worry about error checking or bad user data.

In [5]:
hrs = input("Enter Hours:")
rate = input("Enter Rate:")
h = float(hrs)
r = float(rate)
gross_pay = h * r
print('Pay:', gross_pay)

Enter Hours:35
Enter Rate:2.75
Pay: 96.25


In [ ]:
x = 5
if  x == 5 :
    print('Is 5')
    print('Is Still 5')
    print('Third 5')

In [2]:
x = 6
if x == 6 :
    print('Is 6')
    print('Is Still 6')
    print('Third 6')

Is 6
Is Still 6
Third 6


In [3]:
x = 0
if x < 2 :
    print('Small')
elif x < 10 :
    print('Medium')
else :
    print('LARGE')
print('All done')

Small
All done


In [4]:
x = 2.0
if x < 2 :
    print('Below 2')
elif x >= 2 :
     print('Two or more')
else :
    print('Something else')

Two or more


In [5]:
astr = 'Hello Bob'
istr = int(astr)
print('First', istr)
astr = '123'
istr = int(astr)
print('Second', istr)

ValueError: invalid literal for int() with base 10: 'Hello Bob'

In [6]:
astr = 'Hello Bob'
istr = 0
try:
    istr = int(astr)
except:
    istr = -1

In [7]:
istr

-1

In [ ]:
hrs = input("Enter Hours:")
h = float(hrs)
rate = input("Enter Rate:")
r = float(rate)
ot = 0
if h > 40:
    ot = h - 40  
rate = 10.5
total = (40 * r) + (ot * 1.5 * r)
print(total)

In [1]:
r = 0
h = 0
ot = 0

hrs = input("Enter Hours:")
rate = input("Enter Rate:")

try:
    r = float(rate)
    h = float(hrs)
except:
    print("Error, please enter numeric inputs.")
    
if h > 40:
    ot = h - 40  
total = (40 * r) + (ot * 1.5 * r)
print(total)

Enter Hours:45
Enter Rate:10.5
498.75


## 3.3 

- Write a program to prompt for a score between 0.0 and 1.0. 
- If the score is out of range, print an error. 
- If the score is between 0.0 and 1.0, print a grade using the following table:

Score Grade

In [2]:
score = input("Enter Score: ")

try:
    xs = float(score)
except:
    print("Error, please enter numeric inputs.")
    
if xs >= 0.9:
  print("A")
elif xs >= 0.8:
  print("B")
elif xs >= 0.7:
  print("C")
elif xs >= 0.6:
  print("D")
else:
  print("F")


Enter Score: 0.85
B


## 4.1 - Using Functions

In [3]:
def func1():
    print('Hello')
    print('Goodbye')

In [4]:
func1()

Hello
Goodbye


**Python Reserved Words**

| A | B | C |
|---|---|---|
|False 	|def 	|if |	
|None 	|del 	|import|	
|True 	|elif 	|in|
|and 	|else 	|is|
|as 	|except 	|lambda|
|assert 	|finally 	|nonlocal|
|break 	|for 	|not|
|class 	|from 	|or|
|continue 	|global 	|pass|
|raise |return |try|
|while |with |yield|

In [5]:
big = max('Hello world')
big

'w'

In [6]:
small = min('Hello world')
small

' '

In [7]:
i = 42.0
type(i)

float

In [8]:
# Sample function

def greeting(lang):
    if lang == 'es':
        return('Hola')
    elif lang == 'fr':
        return('Bonjour')
    else: 
        return('Hello')

In [9]:
greeting('es')

'Hola'

In [10]:
greeting('fr')

'Bonjour'

In [11]:
greeting('')

'Hello'

In [12]:
# Example #2

def greet():
    return 'Hola'

print(greeting('es'), "Juan",'\b!')

Hola Juan !


In [13]:
def greet(lang):
    if lang == 'es':
        return 'Hola'
    elif lang == 'fr':
        return 'Bonjour'
    else:
        return 'Hello'

print(greet('fr'),'Michael')

Bonjour Michael


In [14]:
def addtwo(a, b):
    added = a + b
    return a

x = addtwo(2, 7)
print(x)

2


## 4.6 

1. Write a program to prompt the user for hours and rate per hour using input to compute gross pay. 
2. Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. 
3. Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. 
4. The function should return a value. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). 
5. You should use input to read a string and float() to convert the string to a number. 
6. Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. 

7. Do not name your variable sum or use the sum() function.

In [15]:
def computepay(hrs, rate):
    h = float(hrs)
    r = float(rate)
    ot = 0
    if h > 40:
        ot = h - 40  
    total = (h * r) + (ot * 0.5 * r)
    return total

hrs = input("Enter Hours:")

rate = input("Enter Rate:")

p = computepay(hrs, rate)

print("Pay", p)

Enter Hours:45
Enter Rate:10.5
Pay 498.75
