---
title: Coursera-R programming-Assignment-3
owner: MCurcio
data: 12/9/2020
---



```{r message=FALSE, warning=FALSE}
rankhospital <- function(state = "TX", outcome = "heart failure", num) {
      library(tidyverse)
      # Read .csv
      df = read.csv("outcome-of-care-measures.csv",
                    na.strings = "Not Available",
                    skip = 1,
                    header = FALSE,
                    stringsAsFactors = FALSE)
      
      # Retain only hospital, state, ha, hf, p
      df <- df[,c(2,7,11,17,25)]
      all_states <- unique(df[, 2])
      
      # Check for invalid outcome
      if (!(outcome %in% c("heart attack", "heart failure", "pneumonia"))) { 
            stop("invalid outcome") 
      } else { 
          #print("outcome OK") 
          switch(outcome,
                 "heart attack"  = (df <- df[, c(1, 2, 3)]),
                 "heart failure" = (df <- df[, c(1, 2, 4)]),
                 "pneumonia"     = (df <- df[, c(1, 2, 5)]))
      }
      
      # Check for invalid state 
      if (!(state %in% all_states)) { 
            stop("invalid state") 
      } else { 
            #print("state OK") 
            df  <-  df[df[,2] == state,]
            df <- na.omit(df) #remove NAs
      }
      
      # Order by score then hospital name
      df <- df[order(df[,3], df[,1]), ]

      # Check for invalid (number,best,worst)
      if (num == "best") {
            return(head(df, n = 1))
      } else if (num == "worst") {
            return(tail(df, n = 1))
      } else if (is.integer(num)  & num > 50){
            return(NA)
      } else {
            return(df[num, 1])
      }
}
```



```{r}
df <- rankhospital(state = "TX", outcome = "heart failure", 4)
df
```


```{r}
rankhospital("MD", "heart attack", "worst")
```

```{r}
df <- rankhospital(state = "TX", outcome = "heart failure", num = 4)
df
```

```{r}
df <- rankhospital(state = "TX", outcome = "heart failure", num = "best")
df
```
```{r}
df <- rankhospital(state = "TX", outcome = "heart failure", num = "worst")
df
```



```{r}
df <- rankhospital(
           state = "RI", 
           outcome = "heart attack")

head(df)
```

```{r}
df <- best(state = "RI", 
           outcome = "heart battack")

head(df)
```


```{r}
rankhospital("MN", "heart attack", 5000)
```













